[package]
name = "rust"
version = "0.1.0"
authors = ["Tim Boldt <tim.boldt@gmail.com>"]
edition = "2018"

[dependencies]
micromath = { git = 'https://github.com/tarcieri/micromath', branch = 'main' }
